### ISSUE TITLE
can't evaluate field Resources in type *hugolib.Page

### ISSUE THREAD

**Issue by brasilikum** [talves/hugo-resource-images#1]
Hey,
I came here from the discussion on the hugo board and SO.
This repo works for me if I clone it but when I try to recreate it, I always get:

executing "partials/list-resource-images.html" at <.Resources.ByType>: can't evaluate field Resources in type *hugolib.Page

Any idea what could be wrong? Why is this a page and not a section?

Thanks in advance

**Comment by GregHilston** [comment]
Any update on this?

**Comment by brasilikum** [comment]
Hey @GregHilston, I just remember that the error was not actually related to this, it just happened to be caught there. The only advice I can give is to tinker around with your file structure.
I described my approach here: https://github.com/netlify-templates/one-click-hugo-cms/issues/19
